services:
  kv-store:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_DIR=/workspaces/kv-store/storage
    volumes:
      - ..:/workspaces/kv-store
    working_dir: /workspaces/kv-store
    ports:
      - 3000:3000
    tty: true
